In [2]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import statsmodels.formula.api as smf

# Задача 1.1 sleep equation #1

In [22]:
df = pd.read_csv('https://raw.githubusercontent.com/artamonoff/Econometrica/master/python-notebooks/data-csv/sleep75.csv')
df

age  black  case  clerical  construc  educ  earns74  gdhlth  inlf  leis1  \
0     32      0     1  0.000000  0.000000    12        0       0     1   3529   
1     31      0     2  0.000000  0.000000    14     9500       1     1   2140   
2     44      0     3  0.000000  0.000000    17    42500       1     1   4595   
3     30      0     4  0.000000  0.000000    12    42500       1     1   3211   
4     64      0     5  0.000000  0.000000    14     2500       1     1   4052   
..   ...    ...   ...       ...       ...   ...      ...     ...   ...    ...   
701   45      0   702  0.182331  0.030075    12     5500       1     0   5069   
702   34      0   703  0.182331  0.030075    10     2500       0     0   5885   
703   37      0   704  0.182331  0.030075    12     3500       1     0   4719   
704   54      0   705  0.182331  0.030075    17    32500       1     0   5149   
705   30      0   706  0.182331  0.030075    16     6750       1     0   4747   

     ...  spwrk75  totwrk  union  worknrm  workscnd  exper  yngkid  yrsmarr  \
0    ...        0    3438      0     3438         0     14       0       13   
1    ...        0    5020      0     5020         0     11       0        0   
2    ...        1    2815      0     2815         0     21       0        0   
3    ...        1    3786      0     3786         0     12       0       12   
4    ...        1    2580      0     2580         0     44       0       33   
..   ...      ...     ...    ...      ...       ...    ...     ...      ...   
701  ...        1    2026      0     2026         0     27       0       18   
702  ...        0     675      1      465       210     18       0        4   
703  ...        1    1851      0     1851         0     19       0       17   
704  ...        1    1961      1     1481       480     31       0       22   
705  ...        0    2363      0     2363         0      8       1        9   

        hrwage  agesq  
0     7.070004   1024  
1     1.429999    961  
2    20.529997   1936  
3     9.619998    900  
4     2.750000   4096  
..         ...    ...  
701        NaN   2025  
702        NaN   1156  
703        NaN   1369  
704        NaN   2916  
705        NaN    900  

[706 rows x 34 columns]

In [23]:
model = smf.ols(data=df, formula='sleep~totwrk+age+male+smsa+south').fit()
hat_y = model.predict()

In [24]:
hat_y

array([3067.10583631, 2894.49476254, 3150.37075855, 2910.94924531,
       3303.75993003, 3472.6900719 , 3301.14172725, 3023.8804497 ,
       3251.79465914, 3104.60304347, 2591.50610935, 3415.84208454,
       3157.91546836, 3239.22243895, 3168.41882119, 3124.69052876,
       3124.03220455, 2983.72677965, 3263.51683965, 3369.7221562 ,
       3044.02875134, 3060.57363178, 3285.21066833, 3135.81565247,
       2807.46105408, 3101.03250584, 3002.42541199, 3129.80523542,
       3214.60758145, 3188.66233468, 2991.99642153, 3018.92151018,
       3136.97517574, 3199.27100653, 3074.11687847, 2978.93503636,
       3180.58032354, 3450.79249364, 3119.08529912, 3152.00332795,
       3122.41382707, 3150.48016232, 3167.61968067, 3243.68584648,
       3168.42290594, 3243.74401963, 3220.49507817, 3498.46452305,
       3299.07444219, 2768.41983181, 3036.14254043, 3096.3245862 ,
       3227.14627219, 3133.77301111, 3173.5133905 , 3232.01790829,
       3266.75411605, 3224.56832679, 3228.83170859, 3226.16578

In [36]:
df['slp2'] = hat_y**2/3600
df['slp3'] = hat_y**3/216000
df['slp4'] = hat_y**4/12960000
df

age  black  case  clerical  construc  educ  earns74  gdhlth  inlf  leis1  \
0     32      0     1  0.000000  0.000000    12        0       0     1   3529   
1     31      0     2  0.000000  0.000000    14     9500       1     1   2140   
2     44      0     3  0.000000  0.000000    17    42500       1     1   4595   
3     30      0     4  0.000000  0.000000    12    42500       1     1   3211   
4     64      0     5  0.000000  0.000000    14     2500       1     1   4052   
..   ...    ...   ...       ...       ...   ...      ...     ...   ...    ...   
701   45      0   702  0.182331  0.030075    12     5500       1     0   5069   
702   34      0   703  0.182331  0.030075    10     2500       0     0   5885   
703   37      0   704  0.182331  0.030075    12     3500       1     0   4719   
704   54      0   705  0.182331  0.030075    17    32500       1     0   5149   
705   30      0   706  0.182331  0.030075    16     6750       1     0   4747   

     ...  worknrm  workscnd  exper  yngkid  yrsmarr     hrwage  agesq  \
0    ...     3438         0     14       0       13   7.070004   1024   
1    ...     5020         0     11       0        0   1.429999    961   
2    ...     2815         0     21       0        0  20.529997   1936   
3    ...     3786         0     12       0       12   9.619998    900   
4    ...     2580         0     44       0       33   2.750000   4096   
..   ...      ...       ...    ...     ...      ...        ...    ...   
701  ...     2026         0     27       0       18        NaN   2025   
702  ...      465       210     18       0        4        NaN   1156   
703  ...     1851         0     19       0       17        NaN   1369   
704  ...     1481       480     31       0       22        NaN   2916   
705  ...     2363         0      8       1        9        NaN    900   

            slp2           slp3          slp4  
0    2613.093948  133577.261621  6.828260e+06  
1    2327.249981  112270.214669  5.416092e+06  
2    2756.898866  144754.226177  7.600491e+06  
3    2353.784864  114195.804536  5.540303e+06  
4    3031.897132  166944.337613  9.192400e+06  
..           ...            ...           ...  
701  2837.779335  151170.807437  8.052992e+06  
702  3487.073425  205916.732500  1.215968e+07  
703  2952.373837  160419.449635  8.716511e+06  
704  3190.486386  180212.679349  1.017920e+07  
705  2938.870515  159320.139322  8.636960e+06  

[706 rows x 37 columns]

In [37]:
model2 = smf.ols(data=df, formula='sleep~totwrk+age+male+smsa+south+slp2+slp3+slp4').fit()
model2.params

Intercept    659589.097361
totwrk          -43.375569
age             721.677267
male          23252.941195
smsa         -14470.001420
south         25358.789388
slp2           -384.498147
slp3              4.285592
slp4             -0.017787
dtype: float64

In [38]:
R2_un = model2.rsquared
R2_re = model.rsquared

In [39]:
F_obs = (R2_un - R2_re)/(1-R2_un)*(len(df)-9)/3
F_obs.round(3)

2.183

In [40]:
alpha=0.05
stats.f.ppf(1-alpha,3,len(df)-6).round(3)

2.618

$ F_{obs} < F_{cr} \Rightarrow H_0$ не отвеграем

# Задача 1.2 sleep equation #2

In [33]:
df = pd.read_csv('https://raw.githubusercontent.com/artamonoff/Econometrica/master/python-notebooks/data-csv/sleep75.csv')
df

age  black  case  clerical  construc  educ  earns74  gdhlth  inlf  leis1  \
0     32      0     1  0.000000  0.000000    12        0       0     1   3529   
1     31      0     2  0.000000  0.000000    14     9500       1     1   2140   
2     44      0     3  0.000000  0.000000    17    42500       1     1   4595   
3     30      0     4  0.000000  0.000000    12    42500       1     1   3211   
4     64      0     5  0.000000  0.000000    14     2500       1     1   4052   
..   ...    ...   ...       ...       ...   ...      ...     ...   ...    ...   
701   45      0   702  0.182331  0.030075    12     5500       1     0   5069   
702   34      0   703  0.182331  0.030075    10     2500       0     0   5885   
703   37      0   704  0.182331  0.030075    12     3500       1     0   4719   
704   54      0   705  0.182331  0.030075    17    32500       1     0   5149   
705   30      0   706  0.182331  0.030075    16     6750       1     0   4747   

     ...  spwrk75  totwrk  union  worknrm  workscnd  exper  yngkid  yrsmarr  \
0    ...        0    3438      0     3438         0     14       0       13   
1    ...        0    5020      0     5020         0     11       0        0   
2    ...        1    2815      0     2815         0     21       0        0   
3    ...        1    3786      0     3786         0     12       0       12   
4    ...        1    2580      0     2580         0     44       0       33   
..   ...      ...     ...    ...      ...       ...    ...     ...      ...   
701  ...        1    2026      0     2026         0     27       0       18   
702  ...        0     675      1      465       210     18       0        4   
703  ...        1    1851      0     1851         0     19       0       17   
704  ...        1    1961      1     1481       480     31       0       22   
705  ...        0    2363      0     2363         0      8       1        9   

        hrwage  agesq  
0     7.070004   1024  
1     1.429999    961  
2    20.529997   1936  
3     9.619998    900  
4     2.750000   4096  
..         ...    ...  
701        NaN   2025  
702        NaN   1156  
703        NaN   1369  
704        NaN   2916  
705        NaN    900  

[706 rows x 34 columns]

In [9]:
model = smf.ols(data=df, formula='sleep~totwrk+south+totwrk*south+age+age^2+male+smsa+marr').fit()
hat_y = model.predict()

In [10]:
hat_y

array([3059.73210324, 3027.3532931 , 3150.08651553, 2906.22542169,
       3304.32495418, 3480.81361623, 3302.92001791, 3018.64249591,
       3251.64695154, 3103.22487284, 2565.18950959, 3435.48812074,
       3158.75168435, 3237.92262278, 3169.29461401, 3120.06025587,
       3122.75399245, 2972.88448972, 3267.28811204, 3377.97886255,
       3009.64160796, 3056.94109341, 3285.50384309, 3105.60212329,
       2794.37928098, 3094.11963493, 2997.01296231, 3107.78603826,
       3212.83986045, 3185.04950028, 2986.37752476, 3009.99265338,
       3102.52139932, 3196.8985099 , 3071.30306935, 2942.6247526 ,
       3177.60506258, 3462.25764756, 3113.90561167, 3122.66600304,
       3121.69124716, 3146.23996748, 3142.26267596, 3307.58157647,
       3164.02292152, 3242.90995636, 3278.91751039, 3463.61040424,
       3332.14810262, 2749.8503227 , 3027.68114617, 3064.56595296,
       3226.40083164, 3133.45832632, 3144.93985452, 3210.00577965,
       3296.51745717, 3273.4668243 , 3227.90935656, 3224.84555

In [11]:
df['slp2'] = hat_y**2/3600
df['slp3'] = hat_y**3/216000
df['slp4'] = hat_y**4/12960000
df

age  black  case  clerical  construc  educ  earns74  gdhlth  inlf  leis1  \
0     32      0     1  0.000000  0.000000    12        0       0     1   3529   
1     31      0     2  0.000000  0.000000    14     9500       1     1   2140   
2     44      0     3  0.000000  0.000000    17    42500       1     1   4595   
3     30      0     4  0.000000  0.000000    12    42500       1     1   3211   
4     64      0     5  0.000000  0.000000    14     2500       1     1   4052   
..   ...    ...   ...       ...       ...   ...      ...     ...   ...    ...   
701   45      0   702  0.182331  0.030075    12     5500       1     0   5069   
702   34      0   703  0.182331  0.030075    10     2500       0     0   5885   
703   37      0   704  0.182331  0.030075    12     3500       1     0   4719   
704   54      0   705  0.182331  0.030075    17    32500       1     0   5149   
705   30      0   706  0.182331  0.030075    16     6750       1     0   4747   

     ...  worknrm  workscnd  exper  yngkid  yrsmarr     hrwage  agesq  \
0    ...     3438         0     14       0       13   7.070004   1024   
1    ...     5020         0     11       0        0   1.429999    961   
2    ...     2815         0     21       0        0  20.529997   1936   
3    ...     3786         0     12       0       12   9.619998    900   
4    ...     2580         0     44       0       33   2.750000   4096   
..   ...      ...       ...    ...     ...      ...        ...    ...   
701  ...     2026         0     27       0       18        NaN   2025   
702  ...      465       210     18       0        4        NaN   1156   
703  ...     1851         0     19       0       17        NaN   1369   
704  ...     1481       480     31       0       22        NaN   2916   
705  ...     2363         0      8       1        9        NaN    900   

            slp2           slp3          slp4  
0    2600.544595  132616.163077  6.762832e+06  
1    2545.796656  128450.431497  6.481081e+06  
2    2756.401404  144715.048249  7.597749e+06  
3    2346.151723  113640.762993  5.504428e+06  
4    3032.934279  167030.007017  9.198690e+06  
..           ...            ...           ...  
701  2855.613024  152598.066558  8.154526e+06  
702  3509.323478  207890.719727  1.231535e+07  
703  2967.844777  161682.037864  8.808103e+06  
704  3180.504753  179367.631454  1.011561e+07  
705  2967.832804  161681.059461  8.808032e+06  

[706 rows x 37 columns]

In [20]:
model2 = smf.ols(data=df, formula='sleep~totwrk+south+totwrk*south+age+age^2+male+smsa+marr+slp2+slp3+slp4').fit()
model2.params

Intercept       903709.549754
totwrk             -61.179424
south           -13801.077134
totwrk:south        22.051682
age               1014.415240
age ^ 2            -10.817306
male             29839.097230
smsa            -18909.953902
marr             10375.230973
slp2              -547.236782
slp3                 6.415666
slp4                -0.028140
dtype: float64

In [21]:
R2_un = model2.rsquared
R2_re = model.rsquared

In [22]:
F_obs = (R2_un - R2_re)/(1-R2_un)*(len(df)-9)/3
F_obs.round(3)

1.867

In [23]:
alpha=0.05
stats.f.ppf(1-alpha,3,len(df)-6).round(3)

2.618

$ F_{obs} < F_{cr} \Rightarrow H_0$ не отвеграем

# Задача 1.3 output equation #1

In [37]:
df = pd.read_csv('https://raw.githubusercontent.com/ryupepa/Econometrica/master/python-notebooks/data-csv/Labour.csv')
df

capital  labour     output       wage
0     2.606563     184   9.250759  43.080307
1     1.323237      91   3.664310  27.780016
2    22.093692     426  28.781516  44.467748
3    10.737851      72   4.124642  39.734710
4     1.161365      46   2.890150  34.650709
..         ...     ...        ...        ...
564   2.625403      20   1.424376  33.477545
565   1.276386      61   2.109048  26.300732
566   1.953869     117   6.241870  41.153979
567   1.318527      46   7.902237  66.720139
568   2.832391     161   6.804085  36.618435

[569 rows x 4 columns]

In [38]:
model = smf.ols(data=df, formula='output~capital+labour+wage').fit()
hat_y = model.predict()

In [39]:
hat_y

array([ 1.22906950e+01,  4.57101298e-01,  3.26713978e+01,  8.45249490e+00,
        1.15007554e+00,  4.95323301e+02,  4.96225925e-01,  2.69781742e+00,
        6.93083590e-01,  2.43757091e+00,  5.66564085e+00,  1.92791692e+00,
       -2.55367472e-01,  3.71340262e+00,  3.00062549e+00,  5.58104740e+00,
       -5.65128192e+00,  1.60377117e+01,  2.27977417e+00, -1.63642251e+00,
       -5.20310116e+00,  7.25038098e+00,  4.06867541e+00, -6.25486350e-01,
        3.32128894e+00,  4.22318186e+00,  5.97177164e+00,  6.60880530e+00,
        1.37823245e+01,  5.40857894e+00, -1.68422671e+00,  3.97020603e+00,
        1.11408840e+01, -9.36989184e-01,  9.15360522e+00, -6.27008499e-01,
        4.01437577e+00,  1.68675245e+01,  2.41409083e+00,  3.64642225e+00,
        3.49784717e+01,  5.31658996e+00,  3.26044590e+00,  1.96810268e+01,
        7.68688994e+00,  6.09158964e+00,  3.71223636e+01,  6.83356225e-01,
        5.77238852e+00,  2.03922830e+01,  3.94775369e+00,  8.78354170e+00,
        6.07147791e+01,  

In [40]:
df['out2'] = hat_y**2
df['out3'] = hat_y**3
df['out4'] = hat_y**4
df

capital  labour     output       wage         out2          out3  \
0     2.606563     184   9.250759  43.080307   151.061183   1856.646929   
1     1.323237      91   3.664310  27.780016     0.208942      0.095507   
2    22.093692     426  28.781516  44.467748  1067.420235  34874.111139   
3    10.737851      72   4.124642  39.734710    71.444670    603.885709   
4     1.161365      46   2.890150  34.650709     1.322674      1.521175   
..         ...     ...        ...        ...          ...           ...   
564   2.625403      20   1.424376  33.477545     0.006650     -0.000542   
565   1.276386      61   2.109048  26.300732     2.906347     -4.954744   
566   1.953869     117   6.241870  41.153979    61.588363    483.334718   
567   1.318527      46   7.902237  66.720139   231.830599   3529.849074   
568   2.832391     161   6.804085  36.618435    70.702934    594.505886   

             out4  
0    2.281948e+04  
1    4.365659e-02  
2    1.139386e+06  
3    5.104341e+03  
4    1.749466e+00  
..            ...  
564  4.422515e-05  
565  8.446854e+00  
566  3.793126e+03  
567  5.374543e+04  
568  4.998905e+03  

[569 rows x 7 columns]

In [41]:
model2 = smf.ols(data=df, formula='output~capital+labour+wage+out2+out3+out4').fit()
model2.params

Intercept   -1.061334e+01
capital     -9.941386e-02
labour       3.636213e-02
wage         3.498227e-01
out2         6.738526e-03
out3        -1.633088e-05
out4         9.095123e-09
dtype: float64

In [42]:
R2_un = model2.rsquared
R2_re = model.rsquared

In [43]:
F_obs = (R2_un - R2_re)/(1-R2_un)*(len(df)-7)/3
F_obs.round(3)

69.533

In [44]:
alpha=0.05
stats.f.ppf(1-alpha,3,len(df)-7).round(3)

2.621

$ F_{obs} > F_{cr} \Rightarrow H_0$ отвеграем

# Задача 1.4 output equation #2


In [45]:
df = pd.read_csv('https://raw.githubusercontent.com/ryupepa/Econometrica/master/python-notebooks/data-csv/Labour.csv')
df

capital  labour     output       wage
0     2.606563     184   9.250759  43.080307
1     1.323237      91   3.664310  27.780016
2    22.093692     426  28.781516  44.467748
3    10.737851      72   4.124642  39.734710
4     1.161365      46   2.890150  34.650709
..         ...     ...        ...        ...
564   2.625403      20   1.424376  33.477545
565   1.276386      61   2.109048  26.300732
566   1.953869     117   6.241870  41.153979
567   1.318527      46   7.902237  66.720139
568   2.832391     161   6.804085  36.618435

[569 rows x 4 columns]

In [46]:
model = smf.ols(data=df, formula='np.log(output)~np.log(capital)+np.log(labour)+np.log(wage)').fit()
hat_y = model.predict()

In [47]:
hat_y

array([ 2.35989958,  1.34716989,  3.3130779 ,  1.82090689,  1.03983458,
        5.8587148 ,  1.06531002,  1.55498428,  0.81379468,  1.4684784 ,
        1.42691402,  0.72993199,  1.2954135 ,  1.18047975,  1.14403561,
        1.97163239, -1.40792342,  2.64881065,  1.67272941,  0.85864447,
       -0.52432467,  1.62340063,  1.60175018,  0.34378623,  1.47904166,
        1.59523602,  1.82552042,  1.41043394,  2.53071436,  1.8703142 ,
       -0.19605089,  1.56305837,  1.86238377,  0.85801498,  2.17668439,
        1.32592943,  1.34163888,  2.68341674,  1.51511337,  1.10757717,
        3.28302213,  1.82326807,  1.33270466,  0.53995352,  1.56315707,
        1.6835631 ,  3.39917857,  1.1523541 ,  1.62574217,  1.03271288,
        1.65491718,  1.86661549,  3.60003683,  5.0342221 ,  1.73071522,
        5.76252664,  0.48941252,  0.95806217,  0.33583131,  1.03056803,
        2.1978038 ,  3.71648169,  2.87648876,  1.11821811,  0.80414367,
        1.64710272,  0.81197612,  1.56116845,  2.35593082,  3.63

In [48]:
df['out2'] = hat_y**2
df['out3'] = hat_y**3
df['out4'] = hat_y**4
df

capital  labour     output       wage       out2       out3        out4
0     2.606563     184   9.250759  43.080307   5.569126  13.142578   31.015165
1     1.323237      91   3.664310  27.780016   1.814867   2.444934    3.293741
2    22.093692     426  28.781516  44.467748  10.976485  36.365950  120.483226
3    10.737851      72   4.124642  39.734710   3.315702   6.037584   10.993879
4     1.161365      46   2.890150  34.650709   1.081256   1.124327    1.169114
..         ...     ...        ...        ...        ...        ...         ...
564   2.625403      20   1.424376  33.477545   0.280766   0.148770    0.078829
565   1.276386      61   2.109048  26.300732   1.006439   1.009674    1.012919
566   1.953869     117   6.241870  41.153979   3.796779   7.398146   14.415527
567   1.318527      46   7.902237  66.720139   2.763817   4.594771    7.638684
568   2.832391     161   6.804085  36.618435   4.521459   9.614303   20.443587

[569 rows x 7 columns]

In [49]:
model2 = smf.ols(data=df, formula='np.log(output)~np.log(capital)+np.log(labour)+np.log(wage)+out2+out3+out4').fit()
model2.params

Intercept         -4.048210
np.log(capital)    0.126006
np.log(labour)     0.616737
np.log(wage)       0.731668
out2               0.068899
out3              -0.005558
out4              -0.000134
dtype: float64

In [50]:
R2_un = model2.rsquared
R2_re = model.rsquared

In [51]:
F_obs = (R2_un - R2_re)/(1-R2_un)*(len(df)-7)/3
F_obs.round(3)

10.595

In [52]:
alpha=0.05
stats.f.ppf(1-alpha,3,len(df)-7).round(3)

2.621

$ F_{obs} > F_{cr} \Rightarrow H_0$ отвеграем

# Задача 1.5 output equation #3

In [53]:
df = pd.read_csv('https://raw.githubusercontent.com/ryupepa/Econometrica/master/python-notebooks/data-csv/Labour.csv')
df

capital  labour     output       wage
0     2.606563     184   9.250759  43.080307
1     1.323237      91   3.664310  27.780016
2    22.093692     426  28.781516  44.467748
3    10.737851      72   4.124642  39.734710
4     1.161365      46   2.890150  34.650709
..         ...     ...        ...        ...
564   2.625403      20   1.424376  33.477545
565   1.276386      61   2.109048  26.300732
566   1.953869     117   6.241870  41.153979
567   1.318527      46   7.902237  66.720139
568   2.832391     161   6.804085  36.618435

[569 rows x 4 columns]

In [66]:
model = smf.ols(data=df, formula='np.log(output)~np.log(capital)+labour+(labour**2)+np.log(wage)').fit()
hat_y = model.predict()

In [67]:
hat_y

array([ 1.8381479 ,  1.148544  ,  2.9138635 ,  2.34254438,  1.2459745 ,
        7.46996719,  1.35661241,  1.18764945,  1.12974183,  1.69008591,
        1.07678602,  1.0870282 ,  1.45004743,  0.94044655,  1.33081122,
        1.59377779, -0.1597961 ,  2.30854169,  1.35831001,  0.58215871,
       -0.05247648,  1.98503336,  1.46888352,  1.52797977,  1.19938528,
        1.80065473,  2.0063883 ,  2.16594978,  2.09773687,  1.45811185,
        0.37844699,  1.81584236,  2.13664056,  1.3945006 ,  2.05776207,
        0.82523707,  2.02433467,  2.37019293,  1.48836192,  1.17579181,
        2.29338815,  0.98771568,  1.49659526,  0.4972591 ,  1.8933043 ,
        1.64662397,  2.77307897,  1.7983176 ,  1.55930047,  1.02940031,
        1.94145181,  0.96411491,  3.46094438,  4.70541386,  2.22194623,
        5.41947735,  0.91866084,  1.47900039,  0.73803718,  0.95430253,
        2.36017539,  3.05401164,  2.26193333,  1.46371221,  1.1466689 ,
        2.03157218,  0.98603549,  2.2041357 ,  2.16054274,  3.32

In [68]:
df['out2'] = hat_y**2
df['out3'] = hat_y**3
df['out4'] = hat_y**4
df

capital  labour     output       wage      out2       out3       out4
0     2.606563     184   9.250759  43.080307  3.378788   6.210711  11.416206
1     1.323237      91   3.664310  27.780016  1.319153   1.515106   1.740165
2    22.093692     426  28.781516  44.467748  8.490600  24.740451  72.090297
3    10.737851      72   4.124642  39.734710  5.487514  12.854746  30.112812
4     1.161365      46   2.890150  34.650709  1.552452   1.934316   2.410109
..         ...     ...        ...        ...       ...        ...        ...
564   2.625403      20   1.424376  33.477545  2.446751   3.827230   5.986588
565   1.276386      61   2.109048  26.300732  1.156091   1.243048   1.336546
566   1.953869     117   6.241870  41.153979  2.702933   4.443784   7.305848
567   1.318527      46   7.902237  66.720139  3.321487   6.053392  11.032274
568   2.832391     161   6.804085  36.618435  3.009030   5.219631   9.054261

[569 rows x 7 columns]

In [69]:
model2 = smf.ols(data=df, formula='np.log(output)~np.log(capital)+labour+labour**2+np.log(wage)+out2+out3+out4').fit()
model2.params

Intercept         -1.982043
np.log(capital)    0.259583
labour             0.001763
np.log(wage)       0.733601
out2               0.370258
out3              -0.112871
out4               0.006103
dtype: float64

In [70]:
R2_un = model2.rsquared
R2_re = model.rsquared

In [71]:
F_obs = (R2_un - R2_re)/(1-R2_un)*(len(df)-7)/3
F_obs.round(3)

60.976

In [72]:
alpha=0.05
stats.f.ppf(1-alpha,3,len(df)-7).round(3)

2.621

$ F_{obs} > F_{cr} \Rightarrow H_0$ отвеграем